services:
  redis:
    container_name: "redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    networks:
      - public

  redis-exporter:
    image: oliver006/redis_exporter:latest
    command:
      - '--redis.addr=redis:6379'
    ports:
      - "9121:9121"
    networks:
      - public


  # ThrottleX Rate Limiter Service
  throttlex:
    container_name: "throttlex"
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password # Added Redis password
      - PORT=8080
      - LIMIT=10
      - WINDOW=60
      - BURST=5
    ports:
      - "8080:8080"
      - "2112:2112" # Port for Prometheus metrics
    depends_on:
      - redis
    networks:
      - public

  # Prometheus Service for monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus UI port
    networks:
      - public

networks:
  public:
    name: public
    driver: bridge
    external: true