name: Release

on:
  push:
    tags:
      - 'v0.0.1'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -o throttlex ./...

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: throttlex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
